INSERT INTO RES(ID, TYPE_ID, REF, VER) VALUES(101, 1,  'reference', 0);
-- meta schema
-- FieldDef
INSERT INTO RES(ID, TYPE_ID, REF, VER) VALUES(102, 16, 'FieldDef', 0);
INSERT INTO RES(ID, TYPE_ID, REF, VER) VALUES(103, 7,  'FieldDef.name', 0);
INSERT INTO RES(ID, TYPE_ID, REF, VER) VALUES(104, 1,  'FieldDef.doc', 0);
INSERT INTO RES(ID, TYPE_ID, REF, VER) VALUES(105, 16, 'FieldDef.type', 0);
INSERT INTO RES(ID, TYPE_ID, REF, VER) VALUES(106, 0,  'FieldDef.default', 0);
INSERT INTO RES(ID, TYPE_ID, REF, VER) VALUES(107, 1,  'FieldDef.order', 0);
INSERT INTO RES(ID, TYPE_ID, REF, VER) VALUES(108, 18, 'FieldDef.aliases', 0);
INSERT INTO RES(ID, TYPE_ID, REF, VER) VALUES(109, 6,  'FieldDef.mandatory', 0);

INSERT INTO RES(ID, TYPE_ID, REF, VER) VALUES(110, 18, 'Array<FieldDef>', 0);

-- TypeDef
INSERT INTO RES(ID, TYPE_ID, REF, VER) VALUES(113, 7,  'TypeDef.name', 0);
INSERT INTO RES(ID, TYPE_ID, REF, VER) VALUES(114, 1,  'TypeDef.doc', 0);
INSERT INTO RES(ID, TYPE_ID, REF, VER) VALUES(115, 0,  'TypeDef.fields', 0);


INSERT INTO REL(RID, PARENT_ID, FIELD_ID, VALUE_ID, L, VSTR, VDEC) VALUES(1100, 102, 103, NULL, NULL, 'name', NULL);
INSERT INTO REL(RID, PARENT_ID, FIELD_ID, VALUE_ID, L, VSTR, VDEC) VALUES(1110, 102, 104, NULL, NULL, 'doc', NULL);
INSERT INTO REL(RID, PARENT_ID, FIELD_ID, VALUE_ID, L, VSTR, VDEC) VALUES(1120, 102, 105, NULL, NULL, 'type', NULL);
INSERT INTO REL(RID, PARENT_ID, FIELD_ID, VALUE_ID, L, VSTR, VDEC) VALUES(1130, 102, 106, NULL, NULL, 'default', NULL);
INSERT INTO REL(RID, PARENT_ID, FIELD_ID, VALUE_ID, L, VSTR, VDEC) VALUES(1140, 102, 107, NULL, NULL, 'order', NULL);
INSERT INTO REL(RID, PARENT_ID, FIELD_ID, VALUE_ID, L, VSTR, VDEC) VALUES(1150, 102, 108, NULL, NULL, 'aliases', NULL);
INSERT INTO REL(RID, PARENT_ID, FIELD_ID, VALUE_ID, L, VSTR, VDEC) VALUES(1160, 102, 109, NULL, NULL, 'mandatory', NULL);

-- Regular Schema
-- LocalizedString type: record( locale String, value String )
INSERT INTO RES(ID, TYPE_ID, REF, VER) VALUES(1110, 16, 'LocalizedString', 0);
INSERT INTO RES(ID, TYPE_ID, REF, VER) VALUES(1111, 1, 'LocalizedString.locale', 0);
INSERT INTO RES(ID, TYPE_ID, REF, VER) VALUES(1112, 1, 'LocalizedString.value', 0);

INSERT INTO REL(RID, PARENT_ID, FIELD_ID, VALUE_ID, L, VSTR, VDEC) VALUES(1170, 1110, 115, 1111, NULL, 'locale', NULL);
INSERT INTO REL(RID, PARENT_ID, FIELD_ID, VALUE_ID, L, VSTR, VDEC) VALUES(1180, 1110, 115, 1112, NULL, 'value', NULL);
